#%RAML 1.0
---
title: NodeJS Kubernetes Boilerplate
baseUri: https://tokesplatform.org
version: 0.0.1

uses:
  Schemas: schemas/index.raml

/module1:
  get:
    description: A simple endpoint for module1
    responses:
      200:
        body:
          application/json:
            type: string

# /metrics:
#   type: collection
#   get:
#     description: |
#       Retrieve metrics for Prometheus
#     responses:
#       200:
#         body:
#           application/json:
#             type: string
